Repository gravitee-io/gravitee-docs, pull requests merged in 2020-10, with the labels that each got.

#232 docs: improve documentation for installation guide
  pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc
Labels: project: APIM

#235 docs: improve documentation for quickstart
  _data/sidebars/apim_3_x_sidebar.yml
  pages/apim/3.x/dev-guide/dev-guide-policies.adoc
  pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc
  pages/apim/3.x/installation-guide/docker/installation-guide-docker_compose.adoc
  pages/apim/3.x/installation-guide/docker/installation-guide-docker_customize.adoc
  pages/apim/3.x/installation-guide/docker/installation-guide-docker_images.adoc
  pages/apim/3.x/installation-guide/gateway/installation-guide-gateway-configuration.adoc
  pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc
  pages/apim/3.x/installation-guide/repositories/installation-guide-repositories-elasticsearch.adoc
  pages/apim/3.x/installation-guide/repositories/installation-guide-repositories-mongodb.adoc
  pages/apim/3.x/installation-guide/repositories/installation-guide-repositories.adoc
  pages/apim/3.x/installation-guide/with-zip/installation-guide-gateway-install-zip.adoc
  pages/apim/3.x/installation-guide/with-zip/installation-guide-management-ui-install-zip.adoc
  pages/apim/3.x/quickstart/api-consumer/api-consumer-api.adoc
  pages/apim/3.x/quickstart/api-consumer/api-consumer-test.adoc
  pages/apim/3.x/quickstart/api-consumer/api-consumer-ui.adoc
  pages/apim/3.x/quickstart/api-publisher/api-publisher-api.adoc
  pages/apim/3.x/quickstart/api-publisher/api-publisher-ui.adoc
  pages/apim/3.x/quickstart/quickstart-overview.adoc
  pages/apim/3.x/user-guide/publisher/documentation/publish-documentation.adoc
Labels: project: APIM, status: in review

#241 feat: allows to define a custom api-key
  images/apim/3.x/api-publisher-guide/plans-subscriptions/custom-api-key-1.png
  images/apim/3.x/api-publisher-guide/plans-subscriptions/custom-api-key-2.png
  images/apim/3.x/api-publisher-guide/plans-subscriptions/custom-api-key-3.png
  pages/apim/3.x/user-guide/publisher/plans-subscriptions.adoc
Labels: status: tw review

#243 feat: label's dictionary
  images/apim/3.x/api-publisher-guide/manage-apis/graviteeio-manage-apis-labels-1.png
  images/apim/3.x/api-publisher-guide/manage-apis/graviteeio-manage-apis-labels-2.png
  images/apim/3.x/api-publisher-guide/manage-apis/graviteeio-manage-apis-labels-3.png
  pages/apim/3.x/user-guide/publisher/manage-api.adoc
Labels: project: APIM, status: tw review

#234 am: add documentation about the JDBC IdP and rewrite of identity providers documentation
  _data/sidebars/am_3_x_sidebar.yml
  pages/am/3.x/user-guide/identity-provider/user-guide-create-identity-provider.adoc
  pages/am/3.x/user-guide/identity-provider/user-guide-database-identity-providers.adoc
  pages/am/3.x/user-guide/identity-provider/user-guide-enterprise-identity-providers.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-database-identity-provider-inline.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-database-identity-provider-jdbc.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-database-identity-provider-mongodb.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-enterprise-identity-provider-http.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-enterprise-identity-provider-ldap.adoc
Labels: status: tw review

#240 am: add documentation for the Twitter and FranceConnect identity providers
  _data/sidebars/am_3_x_sidebar.yml
  images/am/current/graviteeio-am-userguide-legal-franceconnect-logo.png
  images/am/current/graviteeio-am-userguide-legal-idp-franceconnect.png
  images/am/current/graviteeio-am-userguide-social-idp-twitter.png
  pages/am/3.x/user-guide/identity-provider/user-guide-legal-identity-providers.adoc
  pages/am/3.x/user-guide/identity-provider/user-guide-social-identity-providers.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-legal-identity-provider-franceconnect.adoc
  pages/am/3.x/user-guide/identity-provider/userguide-social-identity-provider-twitter.adoc
Labels: status: tw review

#245 am: users advanced search feature
  images/am/current/graviteeio-am-userguide-um-search-users.png
  pages/am/3.x/user-guide/user-management/user/user-guide-users.adoc
Labels: status: tw review

#257 feat: forward x-forwarded-prefix to the backend endpoint
  pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Labels: status: tw review

#258 feat: allow to define background color of login page
  pages/apim/3.x/installation-guide/configuration/management-ui/installation-guide-management-ui-configuration.adoc
Labels: status: tw review
