Repository gravitee-io/gravitee-docs, pull requests merged in 2021-05, with the labels that each got.

#410 feat: associate sharding tags and tenants to organization
  pages/apim/3.x/user-guide/admin/admin-guide-roles-and-permissions.adoc
Labels: status: tw review

#413 feat: allow to associate a gateway to environments
  pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Labels: status: in review, status: tw review

#420 [AM] add breaking changes notes
  _data/sidebars/am_3_x_sidebar.yml
  pages/am/3.x/breaking-changes/breaking-changes-3.9.adoc
  pages/am/3.x/breaking-changes/breaking-changes.adoc
  pages/am/3.x/installation-guide/installation-guide-migration.adoc
Labels: project: AM, status: tw review

#417 feat(captcha): add bot detection section for AM
  _data/sidebars/am_3_x_sidebar.yml
  images/am/current/graviteeio-am-userguide-bot-detection-snippet.png
  pages/am/3.x/user-guide/bot-detection/user-guide-bot-detection-plugins.adoc
  pages/am/3.x/user-guide/bot-detection/user-guide-bot-detection.adoc
Labels: status: tw review
